import streamlit as st
from groq import Groq
from reportlab.lib.pagesizes import landscape, letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
import feedparser
import re

# --- CONFIGURATION ---
try:
    GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
except:
    st.error("⚠️ Please put your GROQ_API_KEY in Streamlit Secrets!")
    st.stop()

client = Groq(api_key=GROQ_API_KEY)

st.set_page_config(page_title="LinkedGod Pro", layout="wide")
st.title("🎨 LinkedGod: Dark Mode Edition")
st.markdown("Generates **High-Contrast, Dark Mode Carousels** automatically.")

# --- 1. LOGIC ---

RSS_FEEDS = {
    "Product Management": "https://techcrunch.com/category/startups/feed/",
    "AI Agents": "https://www.artificialintelligence-news.com/feed/", 
    "Consulting": "http://feeds.harvardbusiness.org/harvardbusiness",
    "Startup Life": "https://news.ycombinator.com/rss"
}

def clean_text(text):
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    return text

def get_latest_news(niche):
    feed = feedparser.parse(RSS_FEEDS.get(niche))
    if feed.entries:
        return feed.entries[0]
    return None

def generate_content(news_item, niche):
    prompt = f"""
    You are a viral LinkedIn Creator.
    NEWS: {news_item.title}
    SUMMARY: {news_item.summary[:800]}
    
    Output TWO parts separated by "|||".
    
    PART 1: CAPTION
    - Hook + Body + 3 Hashtags.
    
    |||
    
    PART 2: CAROUSEL SLIDES (5 Slides)
    - Format strictly as:
      Slide 1: [Short Title] - [Punchy Subtitle]
      Slide 2: [Main Point] - [2 sentence explanation]
      Slide 3: [Main Point] - [2 sentence explanation]
      Slide 4: [Main Point] - [2 sentence explanation]
      Slide 5: [Summary] - [Call to Action]
    """
    
    completion = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt}],
        model="llama-3.3-70b-versatile",
    )
    return completion.choices[0].message.content

# --- THE DESIGN ENGINE (CANVA STYLE) ---
def on_page(canvas, doc):
    """
    This function paints the background BEFORE the text is added.
    This creates the 'Dark Mode' look.
    """
    width, height = landscape(letter)
    
    # 1. Background Color (Deep Navy Blue)
    canvas.setFillColor(colors.HexColor('#0F172A')) # Modern Dark Slate
    canvas.rect(0, 0, width, height, fill=1)
    
    # 2. Top Accent Line (Gold)
    canvas.setStrokeColor(colors.HexColor('#F59E0B')) # Amber/Gold
    canvas.setLineWidth(4)
    canvas.line(0, height-5, width, height-5)
    
    # 3. Footer Text (Branding)
    canvas.setFillColor(colors.HexColor('#94A3B8')) # Light Grey
    canvas.setFont("Helvetica", 10)
    canvas.drawCentredString(width/2, 20, "Generated by LinkedGod AI • @YourName")

def create_dark_mode_pdf(slide_text):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=landscape(letter),
        topMargin=80,    # Push text down to center it
        bottomMargin=80,
        leftMargin=50,
        rightMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    # High Contrast Title (Gold)
    title_style = ParagraphStyle(
        'DarkTitle',
        parent=styles['Heading1'],
        fontSize=36,
        textColor=colors.HexColor('#FCD34D'), # Bright Gold
        alignment=TA_CENTER,
        leading=40,
        spaceAfter=30
    )
    
    # High Contrast Body (White)
    body_style = ParagraphStyle(
        'DarkBody',
        parent=styles['BodyText'],
        fontSize=20,
        textColor=colors.HexColor('#FFFFFF'), # White
        alignment=TA_CENTER,
        leading=28
    )

    story = []
    
    lines = slide_text.strip().split('\n')
    
    for line in lines:
        if "Slide" in line and ":" in line:
            parts = line.split(":", 1)[1].strip()
            
            if "-" in parts:
                title_txt, body_txt = parts.split("-", 1)
            else:
                title_txt = parts
                body_txt = ""
                
            # Content
            story.append(Spacer(1, 20)) # Vertical centering adjustment
            story.append(Paragraph(clean_text(title_txt), title_style))
            story.append(Spacer(1, 20))
            story.append(Paragraph(clean_text(body_txt), body_style))
            story.append(PageBreak())

    # Build PDF with the Background Painter
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    buffer.seek(0)
    return buffer

# --- 2. THE UI ---

col1, col2 = st.columns([1, 1])

with col1:
    niche = st.selectbox("Select Niche", list(RSS_FEEDS.keys()))
    
    if st.button("🔥 Generate Dark Mode Post"):
        with st.status("Agent Working...", expanded=True):
            st.write("📡 Fetching News...")
            news = get_latest_news(niche)
            
            if news:
                st.write(f"✅ Found: {news.title}")
                
                # Get raw AI text
                full_response = generate_content(news, niche)
                
                try:
                    caption_part, slides_part = full_response.split("|||")
                    st.session_state['caption'] = caption_part.strip()
                    st.session_state['slides'] = slides_part.strip()
                    
                    st.write("🎨 Painting Dark Mode PDF...")
                    pdf_buffer = create_dark_mode_pdf(st.session_state['slides'])
                    st.session_state['pdf_data'] = pdf_buffer
                    
                except:
                    st.error("AI formatting error. Try again.")
            else:
                st.error("Feed unavailable.")

# --- 3. OUTPUTS ---
with col2:
    if 'caption' in st.session_state:
        st.subheader("1. Caption")
        st.text_area("Copy this:", st.session_state['caption'], height=350)
        
        st.subheader("2. Carousel")
        st.download_button(
            label="📥 Download Dark Mode PDF",
            data=st.session_state['pdf_data'],
            file_name="dark_mode_carousel.pdf",
            mime="application/pdf"
        )
