import streamlit as st
from groq import Groq
from reportlab.lib.pagesizes import landscape, letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from duckduckgo_search import DDGS
import textwrap
import datetime

# --- CONFIGURATION ---
# 1. Get your Key from: https://console.groq.com/keys
# 2. Put it in Streamlit Secrets (Settings -> Secrets)
try:
    GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
except:
    st.error("⚠️ Please put your GROQ_API_KEY in Streamlit Secrets!")
    st.stop()

client = Groq(api_key=GROQ_API_KEY)

st.set_page_config(page_title="Content Factory", layout="wide")
st.title("🏭 The Semi-Auto Content Factory")
st.markdown("Search News $\to$ Viral Post $\to$ PDF Carousel (in 30s)")

# --- 1. THE BRAIN (Functions) ---

def get_latest_news(query):
    """Searches DuckDuckGo for latest news on the topic"""
    with DDGS() as ddgs:
        results = list(ddgs.news(query, max_results=1))
        if results:
            return results[0] # Returns title, body, url
        return None

def generate_viral_content(news_item, niche):
    """Uses Llama 3 to write the post and slides"""
    
    prompt = f"""
    You are a top LinkedIn Creator in {niche}.
    NEWS UPDATE: {news_item['title']}
    CONTEXT: {news_item['body']}
    SOURCE: {news_item['url']}

    TASK 1: Write a LinkedIn Post.
    - Hook: Punchy, controversial, or "Breaking News" style.
    - Body: Explain why this matters to {niche} professionals.
    - Ending: A question to drive comments.
    - No hashtags in the middle, only 3 at the end.

    TASK 2: Create a 5-Slide Carousel Outline.
    - Format strictly as:
      Slide 1: [Title]
      Slide 2: [Point 1]
      Slide 3: [Point 2]
      Slide 4: [Point 3]
      Slide 5: [Takeaway]
    """
    
    completion = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt}],
        model="llama3-8b-8192",
    )
    return completion.choices[0].message.content

def create_pdf(text_content, filename="carousel.pdf"):
    """Turns the AI text into a design-ready PDF"""
    c = canvas.Canvas(filename, pagesize=landscape(letter))
    width, height = landscape(letter)
    
    # Extract slides from text
    lines = text_content.split('\n')
    slides = [line for line in lines if "Slide" in line]
    
    if not slides:
        slides = ["Slide 1: Breaking News", "Slide 2: Read the caption"]

    for slide in slides:
        # Dark Mode Design
        c.setFillColor(colors.black)
        c.rect(0, 0, width, height, fill=1)
        
        # Text
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 28)
        
        # Clean the "Slide X:" part for cleaner look
        display_text = slide.split(":", 1)[-1].strip() if ":" in slide else slide
        
        # Wrap text
        wrapped_text = textwrap.wrap(display_text, width=45)
        y = height / 2 + (len(wrapped_text)*15)
        
        for line in wrapped_text:
            c.drawCentredString(width/2, y, line)
            y -= 45
            
        # Branding
        c.setFillColor(colors.yellow)
        c.setFont("Helvetica", 12)
        c.drawString(30, 30, "Generated by AI • Curated by You")
        
        c.showPage()
        
    c.save()
    return filename

# --- 2. THE UI ---

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("1. Pick Your Angle")
    niche = st.selectbox("Select Niche", ["Product Management", "AI Agents", "Management Consulting", "Startup Life"])
    
    if st.button("🔴 Find News & Generate"):
        with st.status("Agent is working...", expanded=True) as status:
            
            # A. Search
            st.write("🔍 Searching Global News...")
            query = f"latest {niche} news trends"
            news = get_latest_news(query)
            
            if not news:
                st.error("No news found. Try again.")
                st.stop()
                
            st.write(f"✅ Found: **{news['title']}**")
            
            # B. Write
            st.write("✍️ Drafting Viral Post...")
            ai_output = generate_viral_content(news, niche)
            
            # Separate Post from Slides (Simple logic)
            # Assuming AI puts slides at the end. 
            # In production, we'd use JSON mode for cleaner separation.
            st.session_state['full_text'] = ai_output
            
            # C. Design
            st.write("🎨 Designing Carousel...")
            pdf_path = create_pdf(ai_output)
            
            with open(pdf_path, "rb") as f:
                st.session_state['pdf_data'] = f.read()
                
            status.update(label="Content Ready!", state="complete", expanded=False)

# --- 3. OUTPUTS ---
with col2:
    if 'full_text' in st.session_state:
        st.subheader("📝 Review & Post")
        
        tab1, tab2 = st.tabs(["LinkedIn Text", "Carousel Preview"])
        
        with tab1:
            st.text_area("Copy to LinkedIn:", st.session_state['full_text'], height=400)
            st.info("💡 Tip: Add your own 1-line opinion at the top to make it personal.")
            
        with tab2:
            st.success("PDF Generated Successfully")
            st.download_button(
                label="📥 Download Carousel PDF",
                data=st.session_state['pdf_data'],
                file_name="viral_carousel.pdf",
                mime="application/pdf"
            )
            st.caption("Upload this as a 'Document' on LinkedIn to get 3x more reach.")
